import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/archive">Archive</Link>
        </li>
        <li>
          <Link to="/imagethumbnail">ImageThumbnail</Link>
        </li>
        <li>
          <Link to="/photofilters">PhotoFilters</Link>
        </li>
        <li>
          <Link to="/loyaltysystem">LoyaltySystem</Link>
        </li>
        <li>
          <Link to="/startvideochat">StartVideoChat</Link>
        </li>
        <li>
          <Link to="/subtitles">Subtitles</Link>
        </li>
        <li>
          <Link to="/videoautoplay">Videoautoplay</Link>
        </li>
        <li>
          <Link to="/videocall">VideoCall</Link>
        </li>
        <li>
          <Link to="/videolibrary">VideoLibrary</Link>
        </li>
        <li>
          <Link to="/video">Video</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
